# Generated by Django 4.0.1 on 2022-01-21 06:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=255, null=True)),
                ('marker_type', models.CharField(choices=[('mw', 'men work'), ('cr', 'crash'), ('cm', 'comment'), ('tc', 'temporary camera'), ('pc', 'pernament camers')], max_length=255, null=True)),
            ],
        ),
    ]
